config/routes.rb
GetoffApp::Application.routes.draw do
  resources :stations

  resources :users

  resources :pusher

  match "*options", controller: "application", action: "options", constraints: { method: "OPTIONS" }

  resources :getoff_infos do
    collection do
      get 'search'
      get 'deal'
    end
  end

  resources :getoff_infos

 

   root :to => 'getoff_infos#index'

end

app/models/getoff_info.rb
class GetoffInfo < ActiveRecord::Base
  attr_accessible :hint, :number, :station_name, :time

  belongs_to :station
end

app/controllers/getoff_infos_controller.rb
class GetoffInfosController < ApplicationController
  # GET /getoff_infos
  # GET /getoff_infos.json
  def index
    @getoff_infos = GetoffInfo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @getoff_infos }
    end
  end

  # GET /getoff_infos/1
  # GET /getoff_infos/1.json
  def show
    @getoff_infos = GetoffInfo.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @getoff_info }
    end
 
 end

  # GET /getoff_infos/new
  # GET /getoff_infos/new.json
  def new
    @getoff_info = GetoffInfo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @getoff_info }
    end
  end

  # GET /getoff_infos/1/edit
  def edit
    @getoff_info = GetoffInfo.find(params[:id])
  end

  # POST /getoff_infos
  # POST /getoff_infos.json
  def create
    respond_to do |format|
    @getoff_info = GetoffInfo.new()
    @getoff_info.station_name = params["station_name"]
    @getoff_info.line_num = params["line_num"]
    @getoff_info.container_num = params["container_num"]
    @getoff_info.hint = params["hint"]
  
  if @getoff_info.save
        if params[:callback]
          format.js { render :json => @getoff_info, :callback => params[:callback]}
        else
          format.html { redirect_to @getoff_info, :notice => 'Getoff info was successfully created.' }
          format.json { render :json => @getoff_info, :status => :created, :location => @getoff_info }
        end
      else
        if params[:callback]
          format.js { render :json => @getoff_info,  :callback => params[:callback]}
        else
          format.html { render :action => "new" }
          format.json { render :json => @getoff_info.errors, :status => :unprocessable_entity }
        end
      end
    end
  end

  # PUT /getoff_infos/1
  # PUT /getoff_infos/1.json
  def update
    @getoff_info = GetoffInfo.find(params[:id])

    respond_to do |format|
      if @getoff_info.update_attributes(params[:getoff_info])
        format.html { redirect_to @getoff_info, :notice => 'Getoff info was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @getoff_info.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /getoff_infos/1
  # DELETE /getoff_infos/1.json
  def destroy
    @getoff_info = GetoffInfo.find(params[:id])
    @getoff_info.destroy

    respond_to do |format|
      format.html { redirect_to getoff_infos_url }
      format.json { head :no_content }
    end
  end

  def search
    station_name = params[:station_name]
    if station_name != nil
      @seats = GetoffInfo.find_all_by_station_name(station_name, :order => "time")
    else
      @seats = nil 
    end
    
    respond_to do |format|
      if params[:callback]
        format.js { render :json => {:seatlist => @seats}, :excluded => :updated_at,:callback => params[:callback]}
      else
        format.json { render json: {:items_by_tag => @seats }}
        format.html { render json: {:items_by_tag => @tagged_item_list}} 
      end
    end
  end

  def index
  end 

end

app/helpers/getoff_infos_helper.rb
module GetoffInfosHelper
end

app/views/getoff_infos/_form.html.erb
<%= form_for(@getoff_info) do |f| %>
  <% if @getoff_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@getoff_info.errors.count, "error") %> prohibited this getoff_info from being saved:</h2>

      <ul>
      <% @getoff_info.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :station_id %><br />
    <%= f.text_field :station_id %>
  </div>
  <div class="field">
    <%= f.label :time %><br />
    <%= f.text_field :time %>
  </div>
  <div class="field">
    <%= f.label :number %><br />
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label :hint %><br />
    <%= f.text_field :hint %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/getoff_infos/_form_4_register.html.erb
<%= form_for(@getoff_info) do |f| %>
  <% if @getoff_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@getoff_info.errors.count, "error") %> prohibited this getoff_info from being saved:</h2>

      <ul>
      <% @getoff_info.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
     <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "당신 어디서 내리나요?:" %>
    <%= f.text_field :station_name %>
  </div>
  <div class="field">
    <%= f.label "몇호선 버터플라이세요?" %>
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label "무슨칸에 계신지 왜 말을 못해요?" %>
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label "자리를 찾는 당신의 힌트는?" %>
    <%= f.text_field :hint %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
    <%= f.hidden_field :time, :value => Time.now.utc.iso8601 %>
 
<% end %>

app/views/getoff_infos/_form_4_search.html.erb
<%= form_tag("/getoff_infos/search",:method => "get", :class => "search_form") do %>
<div class = search>
<div id = "button">
  <%= image_submit_tag "seat_main.png", :id => "icon" %>
</div>
<div id = "text_field">  
  <%= text_field_tag :station_name, nil, :id => "input", :placeholder => "Enter a station name for your seat here!!" %>
  <%= hidden_field_tag(:current_time,Time.now.utc.iso8601) %>
</div>
<% end %>

<script type="text/javascript">
  $(document).ready(function() {
   
    //mouse hove effect on sumit icon
    var newPhoto = new Image();
    newPhoto.src = '/assets/seat_click.png';
    var oldSrc=$('#icon').attr('src');
    
    $('#icon').hover(
      function() {
        $(this).attr('src',newPhoto.src);
      },
      function(){
        $(this).attr('src', oldSrc);
      }
    );
   
   });

    $('form').submit(function() {
      if($('#input').val() == '') {
        $('#input').attr("placeholder", "Please insert a station name");
        $('#input').addClass("ask_to_fill_in")
        return false;
      }
   }); 
</script>


    

app/views/getoff_infos/deal.html.erb
<div>
  COMMING SOON!!!

  실시간 좌석 deal을 위한
    채팅창이 곧 추가됩니다!!
</div>

app/views/getoff_infos/edit.html.erb
<h1>Editing getoff_info</h1>

<%= render 'form' %>

<%= link_to 'Show', @getoff_info %> |
<%= link_to 'Back', getoff_infos_path %>

app/views/getoff_infos/find.html.erb
<p id="notice"><%= notice %></p>

<p> Your Seats are Here!!! </p>

<table>
<tr>
  <td><b>User</b></td>
  <td><b>Station</b></td>
  <td><b>Time</b></td>
  <td><b>Number</b></td>
  <td><b>hint</b></td>
</tr> 

<% @seats.each do |seat_info| %>
<tr>
  <td><%= seat_info.user_id %></td>
  <td><%= seat_info.station_id %></td>
  <td><%= seat_info.time %></td>
  <td><%= seat_info.number %></td>
  <td><%= seat_info.hint %></td>
</tr>

<% end %>
</table>

app/views/getoff_infos/index.html.erb
<%= render 'form_4_search' %>

app/views/getoff_infos/new.html.erb
<div class="register">
<%= form_for(@getoff_info) do |f| %>
  <% if @getoff_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@getoff_info.errors.count, "error") %> prohibited this getoff_info from being saved:</h2>

      <ul>
      <% @getoff_info.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
     <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "당신 어디서 내리나요?:" %>
    <%= f.text_field :station_name %>
  </div>
  <div class="field">
    <%= f.label "몇호선 버터플라이세요?" %>
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label "무슨칸에 계신지 왜 말을 못해요?" %>
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label "자리를 찾는 당신의 힌트는?" %>
    <%= f.text_field :hint %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
    <%= f.hidden_field :time, :value => Time.now.utc.iso8601 %>
 
<% end %>
</div>

app/views/getoff_infos/old-show.html.erb
<h1>Listing getoff_infos</h1>

<table>
  <tr>
    <th>User</th>
    <th>Station</th>
    <th>Time</th>
    <th>Number</th>
    <th>Hint</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>


<% @getoff_infos.each do |getoff_info| %>
  <tr>
    <td><%= getoff_info.user_id %></td>
    <td><%= getoff_info.station_id %></td>
    <td><%= getoff_info.time %></td>
    <td><%= getoff_info.number %></td>
    <td><%= getoff_info.hint %></td>
    <td><%= link_to 'Show', getoff_info %></td>
    <td><%= link_to 'Edit', edit_getoff_info_path(getoff_info) %></td>
    <td><%= link_to 'Destroy', getoff_info, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Getoff info', new_getoff_info_path %>

app/views/getoff_infos/old_form_4_search.html.erb
<%= form_tag("/getoff_infos/search",:method => "get") do %>
<div align="center">
  <%= image_submit_tag("seat_main.png") %>
</div>
<div>  
  <%= text_field_tag 'station_name', :place_holder => 'Enter a station name for your seat here!!' %>
  <%= hidden_field_tag(:current_time,Time.now.utc.iso8601) %>
</div>
<% end %>

app/views/getoff_infos/search.erb
<p id="notice"><%= notice %></p>

<table data-role="table" "table-custom-2" data-mode="reflow" class="ui-body-d ui-shadow table-stripe ui-responsive" data-column-btn-theme="b" data-column-btn-text="Columns to display..." data-column-popup-theme="a">


<thead>
<tr class="ui-bar-b"> 
  <td>역이름</td>
  <td>호선</td>
  <td>등록시간</td>
  <td>탑승칸</td>
  <td>Hint</td>
</tr> 
</thead>
<tbody>
<% if @seats.empty? %>
 <p> No matched seats now </P>
<% else %>
  <% @seats.each do |seat_info| %>
  <tr>
	  <td><%= seat_info.station_name %></td>
	  <td><%= seat_info.line_num %></td>
	  <td><%= seat_info.time %></td>
	  <td><%= seat_info.number %></td>
	  <td><%= seat_info.hint %></td>
    </tr>
  <% end %>
<% end %>
</tbody>
</table>

app/views/getoff_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p> Your Seats are Here!!! </p>

<table data-role="table" id="table-custom-2" data-mode="columntoggle" class="ui-body-d ui-shadow table-stripe ui-responsive" data-column-btn-theme="b" data-column-btn-text="Columns to display..." data-column-popup-theme="a">
<tr>
  <td><b>Station</b></td>
  <td><b>Time</b></td>
  <td><b>Number</b></td>
  <td><b>hint</b></td>
</tr> 

<% @getoff_infos.each do |seat_info| %>
<tr>
  <td><%= seat_info.station_name %></td>
  <td><%= seat_info.time %></td>
  <td><%= seat_info.number %></td>
  <td><%= seat_info.hint %></td>
</tr>

<% end %>
</table>