config/routes.rb
GetoffApp::Application.routes.draw do
  resources :stations

  resources :users

  resources :pusher

  match "*options", controller: "application", action: "options", constraints: { method: "OPTIONS" }

  resources :getoff_infos do
    collection do
      get 'search'
      get 'deal'
    end
  end

  resources :getoff_infos

 

   root :to => 'getoff_infos#index'

end

app/models/station.rb
require "rubygems"
require "json"
require "net/http"
require "uri"

class Station < ActiveRecord::Base
  attr_accessible :line, :name, :code, :fr_code

  has_many :getoff_info


	#GET ActiveRecord connection
	def self.do_insert(name,code,line,fr_code)
	  Station.create(:name => name, :code => code, :line => line, :fr_code => fr_code)
	end

    def self.refresh
      auth_key = "66696c6d383232313230"
	  type = "json"
	  target = "SearchSTNBySubwayLineService"
	  idx_start = "1"
	  idx_end = "200"
	  line_list = ["1","2","3","4","5","6","7","8","9","I","K","B","J","A","G"]
	
        line_list.each do |line_number|
	    
		uri = URI.parse("http://openAPI.seoul.go.kr:8088/#{auth_key}/#{type}/#{target}/#{idx_start}/#{idx_end}/#{line_number}")
		http = Net::HTTP.new(uri.host, uri.port)
		request = Net::HTTP::Get.new(uri.request_uri)
		
		response = http.request(request)
		
		if response.code == "200"
		
		  # API response with header
		  result = JSON.parse(response.body)
		  
		  # parse data to get rid of header info
		  data = result["SearchSTNBySubwayLineService"] 
		  list_total_cnt = data["list_total_count"]
		  st_list_arr = data["row"]
		  
		  # extract each station info
		  st_list_arr.each do |st|
		    name = st["STATION_NM"]
	        code = st["STATION_CD"]
	        line = st["LINE_NUM"]
	        fr_code = st["FR_CODE"]
	
	        do_insert(name,code,line,fr_code)
            #Station.create(:name => name, :code => code, :line => line, :fr_code => fr_code)
          end
		else
		  puts "ERROR!!!"
		end
	end
    end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  # GET /stations
  # GET /stations.json
  def index
    @stations = Station.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @stations }
    end
  end

  # GET /stations/1
  # GET /stations/1.json
  def show
    @station = Station.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @station }
    end
  end

  # GET /stations/new
  # GET /stations/new.json
  def new
    @station = Station.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @station }
    end
  end

  # GET /stations/1/edit
  def edit
    @station = Station.find(params[:id])
  end

  # POST /stations
  # POST /stations.json
  def create
    @station = Station.new(params[:station])

    respond_to do |format|
      if @station.save
        format.html { redirect_to @station, :notice => 'Station was successfully created.' }
        format.json { render :json => @station, :status => :created, :location => @station }
      else
        format.html { render :action => "new" }
        format.json { render :json => @station.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /stations/1
  # PUT /stations/1.json
  def update
    @station = Station.find(params[:id])

    respond_to do |format|
      if @station.update_attributes(params[:station])
        format.html { redirect_to @station, :notice => 'Station was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @station.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /stations/1
  # DELETE /stations/1.json
  def destroy
    @station = Station.find(params[:id])
    @station.destroy

    respond_to do |format|
      format.html { redirect_to stations_url }
      format.json { head :no_content }
    end
  end

  def refresh
    Station.refresh
  end
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/views/stations/_form.html.erb
<%= form_for(@station) do |f| %>
  <% if @station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@station.errors.count, "error") %> prohibited this station from being saved:</h2>

      <ul>
      <% @station.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :line %><br />
    <%= f.text_field :line %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stations/edit.html.erb
<h1>Editing station</h1>

<%= render 'form' %>

<%= link_to 'Show', @station %> |
<%= link_to 'Back', stations_path %>

app/views/stations/index.html.erb
<h1>Listing stations</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Code</th>
    <th>Line</th>
    <th>FR_Code</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stations.each do |station| %>
  <tr>
    <td><%= station.name %></td>
    <td><%= station.code %></td>
    <td><%= station.line %></td>
    <td><%= station.fr_code %></td>
    <td><%= link_to 'Show', station %></td>
    <td><%= link_to 'Edit', edit_station_path(station) %></td>
    <td><%= link_to 'Destroy', station, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Station', new_station_path %>

app/views/stations/new.html.erb
<h1>New station</h1>

<%= render 'form' %>

<%= link_to 'Back', stations_path %>

app/views/stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @station.name %>
</p>

<p>
  <b>Line:</b>
  <%= @station.line %>
</p>


<%= link_to 'Edit', edit_station_path(@station) %> |
<%= link_to 'Back', stations_path %>